name: Build/upload sdist and wheel Package to PyPI

on:
  pull_request:
    branches:
      - develop
    paths-ignore:
      - 'example/**'
      - 'docs/**'
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel twine flake8
    - name: Create sdist and wheel
      run: |
        python setup.py sdist bdist_wheel
    - name: Upload artifacts for inspection
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/*
    - name: Publish sdist and wheel to PyPI
      if: github.event_name == 'release' && github.event.action == 'published'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_FORLILAB }}
      run: |
        twine upload dist/*
